### ISSUE TITLE
CDK_AWS_PARTITION: Does not fix the OIDC region and audience.

### ISSUE THREAD

**Issue by oliott** [cdklabs/cdk-pipelines-github#1091]
Hi, 

Setting the environment variable `CDK_AWS_PARTITION` as specified here: [AWS China partition support](https://github.com/cdklabs/cdk-pipelines-github?tab=readme-ov-file#aws-china-partition-support), does not make sure that the `audience` and `aws-region` of this action: [aws-actions/configure-aws-credentials@v4](https://github.com/marketplace/actions/configure-aws-credentials-action-for-github-actions) are configured correctly.

This results in the following: 

<details>
    <summary> pipeline-definition.yml </summary>

```yaml
# AUTOMATICALLY GENERATED FILE, DO NOT EDIT MANUALLY.
# Generated by AWS CDK and [cdk-pipelines-github](https://github.com/cdklabs/cdk-pipelines-github)

name: deploy-china-partition
on:
  push:
    branches:
      - main
  workflow_dispatch: {}
jobs:
# ... other steps
  Assets-FileAsset1:
    name: Publish Assets Assets-FileAsset1
    needs:
      - Build-Build
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    outputs:
      asset-hash: ${{ steps.Publish.outputs.asset-hash }}
    steps:
      - name: Download cdk.out
        uses: actions/download-artifact@v4
        with:
          name: cdk.out
          path: cdk.out
      - name: Install
        run: npm install --no-save cdk-assets
      - name: Authenticate Via OIDC Role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-west-1
          role-duration-seconds: 1800
          role-skip-session-tagging: true
          role-to-assume: arn:aws-cn:iam::000000000000:role/DummyOIDCRole
      - id: Publish
        name: Publish Assets-FileAsset1
        run: /bin/bash ./cdk.out/assembly-DummyStage/publish-Assets-FileAsset1-step.sh
# ... other steps

```
</details>

The `aws-region` part can be fixed by setting [publishAssetsAuthRegion](https://github.com/cdklabs/cdk-pipelines-github/blob/main/src/pipeline.ts#L214), when creating the pipeline. However the audience is not set to `sts.amazonaws.com.cn` which is a requirement for the OIDC authentication to work: [OIDC Audience](https://github.com/marketplace/actions/configure-aws-credentials-action-for-github-actions#oidc-audience). Because of this the github action to assume the OIDC role will fail. 

Relevant issues:
* [ Add support for aws-cn partition #820 ](https://github.com/cdklabs/cdk-pipelines-github/issues/820)

## Reproducible python code:

<details>
    <summary> requirements.txt </summary>

```
aws-cdk-lib==2.154.0
constructs>=10.0.0,<11.0.0
cdk-pipelines-github
```
</details>

<details>
    <summary> app.py </summary>

```python
#!/usr/bin/env python3

import aws_cdk as cdk

from constructs import Construct
from cdk_pipelines_github import GitHubWorkflow, AwsCredentials

app = cdk.App()


class DummyStack(cdk.Stack):
    def __init__(self, scope: Construct, construct_id: str, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)

        cdk.aws_sqs.Queue(
            self,
            "IssueGithubPipelinesQueue",
            visibility_timeout=cdk.Duration.seconds(300),
        )


class DummyPipelineStage(cdk.Stage):
    def __init__(self, scope: Construct, construct_id: str, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)

        DummyStack(self, f"TestStack", **kwargs)


github_pipeline = GitHubWorkflow(
    app,
    "GithubPipeline",
    synth=cdk.pipelines.ShellStep(
        "Build",
        commands=[
            "npm install -g aws-cdk",
            "python -m pip install -r requirements.txt",
            "cdk synth",
        ],
    ),
    aws_creds=AwsCredentials.from_open_id_connect(
        git_hub_action_role_arn=f"arn:aws-cn:iam::000000000000:role/DummyOIDCRole"
    ),
    workflow_name="deploy-china-partition",
    workflow_path=".github/workflows/deploy-china-partition.yml",
    publish_assets_auth_region="cn-northwest-1",
)
wave = github_pipeline.add_wave("MultiRegion")

stage = DummyPipelineStage(
    app,
    "DummyStage",
    env=cdk.Environment(account="000000000000", region="cn-north-west-1"),
)

wave.add_stage(
    stage,
)

app.synth()
```
</details>

### Version
Python 3.10.0
cdk-pipelines-github version: cdk-pipelines-github==0.4.124

### Modifications/environment/deployment
I Have made no modifactions to code environment or deployment that should affect this.

### Issue
Setting the environment variable `CDK_AWS_PARTITION` does not setup the OIDC Github Action correctly.

**Comment by kaizencc** [comment]
@mbergkvist since you were the one helping out with the AWS_PARTITION i'm wondering if you can help here? 
@oliott thanks for bringing this to our attention but i don't currently have time to work on this. i would be happy to review a PR from you or anyone else in the community though. sorry about that -- this is a cdklabs project that relies heavily on community contributions for new features.

**Comment by mbergkvist** [comment]
@oliott `audience` is not set, but that has not been an issue here. Before we go down that path, can you try to add

```yml
env:
  AWS_STS_REGIONAL_ENDPOINTS: regional
```

to the deploy file? In TS it's done with

```typescript
pipeline.workflowFile.patch(JsonPatch.add('/env', { AWS_STS_REGIONAL_ENDPOINTS: 'regional' }));
```

If that doesn't help, please provide the error you get and also how you've setup the trust in the `git_hub_action_role`.

**Comment by oliott** [comment]
Hi thanks for taking time to respond and look at this. I tried setting this:

```yaml
env:
  AWS_STS_REGIONAL_ENDPOINTS: regional
```
But does not really fix the issue. I can paste the entire workflow yaml file here: 

<details>
    <summary> .github/workflows/deploy-china-partition.yml </summary>

```
# AUTOMATICALLY GENERATED FILE, DO NOT EDIT MANUALLY.
# Generated by AWS CDK and [cdk-pipelines-github](https://github.com/cdklabs/cdk-pipelines-github)

name: deploy-china-partition
on:
  push:
    branches:
      - main
  workflow_dispatch: {}
jobs:
  Build-Build:
    name: Synthesize
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    needs: []
    env: {}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |-
          npm install -g aws-cdk
          python -m pip install -r requirements.txt
          cdk synth
      - name: Upload cdk.out
        uses: actions/upload-artifact@v4
        with:
          name: cdk.out
          path: cdk.out
  Assets-FileAsset1:
    name: Publish Assets Assets-FileAsset1
    needs:
      - Build-Build
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    outputs:
      asset-hash: ${{ steps.Publish.outputs.asset-hash }}
    steps:
      - name: Download cdk.out
        uses: actions/download-artifact@v4
        with:
          name: cdk.out
          path: cdk.out
      - name: Install
        run: npm install --no-save cdk-assets
      - name: Authenticate Via OIDC Role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: cn-northwest-1
          role-duration-seconds: 1800
          role-skip-session-tagging: true
          role-to-assume: arn:aws-cn:iam::000000000000:role/DummyOIDCRole
      - id: Publish
        name: Publish Assets-FileAsset1
        run: /bin/bash ./cdk.out/assembly-DummyStage/publish-Assets-FileAsset1-step.sh
  DummyStage-TestStack-Deploy:
    name: Deploy DummyStageTestStackB0404510
    permissions:
      contents: read
      id-token: write
    needs:
      - Build-Build
      - Assets-FileAsset1
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate Via OIDC Role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: cn-north-west-1
          role-duration-seconds: 1800
          role-skip-session-tagging: true
          role-to-assume: arn:aws-cn:iam::000000000000:role/DummyOIDCRole
      - name: Assume CDK Deploy Role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: cn-north-west-1
          role-duration-seconds: 1800
          role-skip-session-tagging: true
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ env.AWS_SESSION_TOKEN }}
          role-to-assume: arn:aws:iam::000000000000:role/cdk-hnb659fds-deploy-role-000000000000-cn-north-west-1
          role-external-id: Pipeline
      - id: Deploy
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: DummyStage-TestStack
          template: https://cdk-hnb659fds-assets-000000000000-cn-north-west-1.s3.cn-north-west-1.amazonaws.com/${{
            needs.Assets-FileAsset1.outputs.asset-hash }}.json
          no-fail-on-empty-changeset: "1"
          role-arn: arn:aws:iam::000000000000:role/cdk-hnb659fds-cfn-exec-role-000000000000-cn-north-west-1
env:
  AWS_STS_REGIONAL_ENDPOINTS: regional
  TEST_ACCOUNT_ID: ${{ vars.TEST_ACCOUNT_ID }}
  TEST_OIDC_ROLE_NAME: ${{ vars.TEST_OIDC_ROLE_NAME }}
```
</details>

The jobs/steps that are failing is the `aws-actions/configure-aws-credentials@v4` since they do not get their audience set to `sts.amazonaws.com.cn`. 

This is the resulting job/step running in github:
```yaml
# Run aws-actions/configure-aws-credentials@v4
  with:
    aws-region: cn-northwest-1
    role-duration-seconds: 1800
    role-skip-session-tagging: true
    role-to-assume: arn:aws-cn:iam::000000000000:role/DummyOIDCRole
    audience: sts.amazonaws.com
  env:
    AWS_STS_REGIONAL_ENDPOINTS: regional
    TEST_ACCOUNT_ID: 000000000000
    TEST_OIDC_ROLE_NAME: DummyOIDCRole
```

So the audience ends up pointing to Europe regardless of me setting that environment variable.

**Comment by mbergkvist** [comment]
@oliott Interesting. I see now that I too have `audience: sts.amazonaws.com` in the logs, but I've no issues with uploading assets or deploying.

```
Run aws-actions/configure-aws-credentials@v4
  with:
    aws-region: cn-north-1
    role-duration-seconds: 1800
    role-skip-session-tagging: true
    role-to-assume: arn:aws-cn:iam::000000000000:role/GitHubActionRole
    role-session-name: GitHubActionsPipeline
    audience: sts.amazonaws.com
  env:
    AWS_STS_REGIONAL_ENDPOINTS: regional
Assuming role with OIDC
Authenticated as assumedRoleId AROAQ4U57LWRXIREWVCNN:GitHubActionsPipeline
```

Could it be the `subject-claims` of the `GitHubActionRole` that is not correct?

```
subjectClaims: ['repo:owner/repo:ref:refs/heads/main'],
```
