### ISSUE TITLE
Set `defaults` for GHA job

### ISSUE THREAD

**Issue by danieljamesscott** [cdklabs/cdk-pipelines-github#299]
I would like to run the pipeline actions in a working directory under my repository root. e.g. My CDK app files are in `./cdk/`. I currently do this using:

```
  test:
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cdk
```

Is there a way to pass a `defaults` block into the pipeline config?
