### ISSUE TITLE
Ability to set a top-of-file comment on deploy.yaml

### ISSUE THREAD

**Issue by giseburt** [cdklabs/cdk-pipelines-github#349]
To aid on-boarding and also to be able to describe what's being deployed.

For example, the following as the first few lines of the `deploy.yml` file:

```yaml
# This file is auto generated. Please see the ReadMe.md for instructions.
# DO NOT MODIFY THIS FILE DIRECTLY
# This file is configured to deploy to:
#  - uat
#  - uat2

name: deploy
on:
  push:
    branches:
# ...
```

The api for this could be simple:

```ts
const preparedComment = `# This file is auto generated. Please see the ReadMe.md for instructions.
# DO NOT MODIFY THIS FILE DIRECTLY
# This file is configured to deploy to:
${ENVS_TO_DEPLOY_TO.map((e) => `  - ${e.name}\n`)}
`;

const pipeline = /*...*/;
pipeline.workflowFile.commentBefore = preparedComment;
```

This would need to be built-in, otherwise it'll invalidate/break the `diffProtection`, which is undesirable.

I believe the code for this wouldn't be too complicated. The only issue I see is the old version of the `yaml` that's being used has a different API for these functions. At this point, I believe switching to the newer `yaml` library would be trivial, but these changes in particular would use the parts of the API that have changed.

If interested, I could work up a PR.
