### ISSUE TITLE
Adding a `GithubActionStep` to the `postBuildSteps` on a `GithubWorkflow` outputs invalid deploy.yml

### ISSUE THREAD

**Issue by michael-lowe-nz** [cdklabs/cdk-pipelines-github#762]
I wanted to use the `postBuildSteps` parameter on the GithubWorkflow to upload some of the test artifacts for download later that are available after running the build steps.

```ts
const pipeline = new GitHubWorkflow(app, "Pipeline", {
  synth: new ShellStep("App", {
    commands: ["yarn", "yarn build"],
  }),
  preBuildSteps: [
    new GitHubActionStep("UploadHTML", {
      jobSteps: [
        {
          name: "UploadTestReports",
          uses: "actions/upload-artifact@v3",
          with: {
            name: "Test Reports",
            path: "test-reports",
          },
        },
      ],
    }),
  ],
});
```

However, the output in the `.github/workflows/deploy.yml` ends up being:

```yml
name: deploy
on:
  push:
    branches:
      - main
  workflow_dispatch: {}
jobs:
  Build-App:
    name: Synthesize
    permissions:
      contents: read
      id-token: none
    runs-on: ubuntu-latest
    needs: []
    env: {}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - id: UploadHTML ### This is the generated step
        dependency-file-sets: []
        is-source: false
        _dependencies: {}
        job-steps:
          - name: UploadTestReports
            uses: actions/upload-artifact@v3
            with:
              name: Test Reports
              path: test-reports
        env: {}
```
This is invalid GH actions config, and to me it looks like there is all sorts of "extra stuff" being thrown in (`id`, `dependency-file-sets`) and the job-steps is a level too deep.
I would have expected it to behave in the same way as the `pre` and `post` hooks for the `addStage` method.

Am I doing something wrong here or is this not supported yet?
