### ISSUE TITLE
Support ghcr docker registry

### ISSUE THREAD

**Issue by corymhall** [cdklabs/cdk-pipelines-github#843]
Currently the `DockerCredential` class supports a custom registry option, but the [implementation](https://github.com/cdklabs/cdk-pipelines-github/blob/07c2661aca38bb2e67685e7f4f0824fcc7b060b2/src/pipeline.ts#L796-L799) expects everything to be stored in a secret.

To configure the ghcr.io (GitHub packages) registry you do this

```yml
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
```

I think there should be a new method (`customRegistryV2`?) that puts the responsibility on the user to provide the entire string rather than just the secret key.

```ts
DockerCredential.customRegistryV2('ghcr.io', {
  username: '${{ github.actor }}',
  password: '${{ secrets.GITHUB_TOKEN }}',
})

```
