### ISSUE TITLE
`cdk synth` from a Windows host results in backslashes in paths.

### ISSUE THREAD

**Issue by jsadoski-rockhall** [cdklabs/cdk-pipelines-github#877]
When running `cdk synth` from my local machine, paths to the file assets in deploy.yml are generated with Windows-style backslashes:

`./cdk.out/assembly-OnstageCms\publish-Assets-FileAsset5-step.sh`

When I commit this file, it fails in my pipeline, because it detects that the deploy.yml is different from what it generated. I also assume these paths won't work even if the check somehow allowed this diff.

If I fix the paths manually, then commit and push, my pipelines deploy successfully.

Here's a sample from my deploy.yml with the issue:

```yaml
  Assets-FileAsset5:
    name: Publish Assets Assets-FileAsset5
    needs:
      - Build-Build-Cloudformation-Templates
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    outputs:
      asset-hash: ${{ steps.Publish.outputs.asset-hash }}
    steps:
      - name: Download cdk.out
        uses: actions/download-artifact@v3
        with:
          name: cdk.out
          path: cdk.out
      - name: Install
        run: npm install --no-save cdk-assets
      - name: Authenticate Via OIDC Role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-west-2
          role-duration-seconds: 1800
          role-skip-session-tagging: true
          role-to-assume: arn:aws:iam::<redacted>:role/GithubActionsForStrapi
      - id: Publish
        name: Publish Assets-FileAsset5
        run: /bin/bash ./cdk.out/assembly-OnstageCms\publish-Assets-FileAsset5-step.sh
```

Environment: Windows 11
Node version: v18.18.2
Package manager: Yarn 4.1.0
cdk-pipelines-github: 0.4.110
